name: OTX IOC Fetch

on:
  schedule:
    - cron: '0 9 * * *'  

jobs:
  fetch-iocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch IOCs from OTX
        run: |
          
